import { useState } from "react";
import { runMoonAgent } from "../../lib/ai/api";
import { aiErrorState, type AIErrorState } from "../../lib/ai/errors";
import { useI18n } from "../../lib/I18nContext";

type Insight = { summary: string; occupancy_risk: string; lead_quality_summary: string; recommended_actions: string[]; pricing_suggestions: string[]; rooms_needing_attention: string[]; confidence_score: number };
export function OperatorInsightsCard({ data }: { data: Record<string, unknown> }) {
  const t = useI18n();
  const [result, setResult] = useState<Insight | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<AIErrorState | null>(null);
  async function analyze() { setBusy(true); setError(null); try { const response = await runMoonAgent<Insight>("operatorInsightsAgent", data, { force: true }); setResult(response.result); } catch (e) { setError(aiErrorState(e, t.ai.operatorFallbackError, t.ai)); } finally { setBusy(false); } }
  return <section className="rounded-xl border border-border-light bg-surface-container-lowest p-6 card-shadow"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-label-sm uppercase tracking-wider text-teal-accent">{t.ai.operatorLabel}</p><h3 className="text-headline-sm text-deep-navy">{t.ai.operatorTitle}</h3></div><button type="button" onClick={analyze} disabled={busy} className="rounded-lg bg-deep-navy px-4 py-2 text-label-sm text-white disabled:opacity-60">{busy ? t.ai.operatorBusy : t.ai.operatorAction}</button></div>{error && <AIErrorNotice error={error} busy={busy} onRetry={analyze} retryText={t.ai.retryButton} retryAfterText={t.ai.retryAfter} />}{result && <div className="mt-4 space-y-3 text-body-sm text-warm-slate"><p>{result.summary}</p><p><strong className="text-deep-navy">{t.ai.occupancyRisk}</strong> {result.occupancy_risk}</p><p><strong className="text-deep-navy">{t.ai.leadQuality}</strong> {result.lead_quality_summary}</p><ul>{result.recommended_actions.map((item) => <li key={item}>• {item}</li>)}</ul></div>}</section>;
}
function AIErrorNotice({ error, busy, onRetry, retryText, retryAfterText }: { error: AIErrorState; busy: boolean; onRetry: () => void; retryText: string; retryAfterText: string }) { return <div className="mt-3 rounded-lg bg-error-container px-4 py-3 text-body-sm text-on-error-container"><p>{error.message}{error.retryAfter ? ` ${retryAfterText.replace("{seconds}", String(error.retryAfter))}` : ""}</p>{error.retryable && <button type="button" disabled={busy} onClick={onRetry} className="mt-3 rounded-lg bg-deep-navy px-3 py-2 text-label-sm text-white disabled:opacity-60">{retryText}</button>}</div>; }
