export const es = {
  brand: ": moon",
  brandProduct: ": moon shared living",
  nav: {
    discover: "Descubrir",
    matches: "Compañeros",
    messages: "Mensajes",
    dashboard: "Mi espacio",
    myProfile: "Ver mi espacio",
    home: "Ir al inicio de la app",
    openMenu: "Abrir menú de cuenta",
    community: "Comunidad",
  },
  common: {
    loading: "Cargando…",
    loadingApplications: "Cargando solicitudes…",
    errorLoad: "No se pudieron cargar los datos.",
    search: "Buscar",
    perMonth: "al mes",
    compatible: "compatible",
    vibeMatch: "afinidad",
    save: "Guardar",
    saved: "Guardado",
    cancel: "Cancelar",
    close: "Cerrar",
    back: "Volver",
    signIn: "Iniciar sesión",
    signOut: "Cerrar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    fullName: "Nombre completo",
    role: "Tu rol en : moon",
    selectRole: "Selecciona cómo usarás la plataforma",
    rememberMe: "Recordarme 30 días",
    forgotPassword: "¿Has olvidado la contraseña?",
    pleaseWait: "Un momento…",
    optional: "Opcional",
    skipForNow: "Lo haré más tarde",
    noResults: "No hay resultados.",
    exploreSpaces: "Explorar pisos",
    edit: "Editar",
    create: "Crear",
    delete: "Eliminar",
    publish: "Publicar",
    view: "Ver",
    viewAll: "Ver todas",
    actions: "Acciones",
  },
  panel: {
    title: "Panel de gestión",
    welcome: "Hola",
    statsListings: "Pisos",
    statsPublished: "Publicados",
    statsApplications: "Solicitudes pendientes",
    myListings: "Mis pisos",
    portfolio: "Cartera de pisos",
    hostSpaces: "Habitaciones asignadas",
    newListing: "Nuevo piso",
    publishModalTitle: "Publicar piso",
    nameSlugRequired: "El nombre y la URL del piso son obligatorios.",
    editListing: "Editar piso",
    noListings: "Aún no tienes pisos publicados.",
    noHostSpaces: "Aún no has publicado ninguna habitación.",
    createFirst: "Publica tu primer piso",
    applications: "Solicitudes de membresía",
    noApplications: "No hay solicitudes para revisar.",
    convivenciaTitle: "Convivencia en tus pisos",
    convivenciaSubtitle:
      "Revisa quién quiere unirse y explora perfiles compatibles antes de decidir.",
    viewRoommates: "Ver compañeros compatibles",
    applicant: "Solicitante",
    space: "Piso",
    approve: "Aprobar",
    reject: "Rechazar",
    interview: "Programar entrevista",
    review: "Revisión final",
    status: "Estado",
    listingStatus: {
      draft: "Borrador",
      published: "Publicado",
      archived: "Archivado",
    },
    deleteListing: "Eliminar anuncio",
    deleteListingConfirm:
      "¿Eliminar este anuncio? Se borrarán fotos, servicios y solicitudes asociadas. Esta acción no se puede deshacer.",
    form: {
      name: "Nombre del piso",
      slug: "URL (slug)",
      location: "Zona",
      city: "Ciudad",
      price: "Precio mensual",
      currency: "Moneda",
      roomType: "Tipo de habitación",
      description: "Descripción",
      coverUrl: "Imagen de portada",
      gallery: "Galería de fotos",
      galleryHint: "Sube varias fotos de la habitación y zonas comunes. La portada también cuenta como primera imagen.",
      addPhotos: "Añadir fotos",
      coverBadge: "Portada",
      amenities: "Servicios incluidos",
      category: "Categoría",
      propertyType: "Tipo de inmueble",
      availableFrom: "Disponible desde",
      host: "Anfitrión asignado",
      hostAdminOnly: "La asignación de anfitriones la gestiona el equipo de : moon.",
      noHost: "Sin anfitrión (solo propietario)",
      visibility: "Visibilidad del anuncio",
      visibilityPublic: "Público — visible en Descubrir",
      visibilityPrivate: "Privado — solo grupos o personas que desbloquees",
      visibilityPrivateHint:
        "Ideal si quieres elegir con quién comparte tu piso. Tras publicar podrás desbloquear grupos concretos.",
      clientName: "Nombre del cliente (agencia)",
      saveDraft: "Guardar borrador",
      publish: "Publicar piso",
      conditions: "Condiciones del alquiler",
      conditionsHint:
        "Duración mínima, fianza, gastos incluidos, normas de convivencia, mascotas, etc. Los inquilinos las verán antes de solicitar.",
      conditionsPlaceholder:
        "Ej. Fianza 2 meses · Gastos incluidos · Mínimo 6 meses · No fumar en interiores…",
      propertyVerification: "Verificación del inmueble",
      propertyVerificationHint:
        "Opcional. Cuando quieras, confirmamos titularidad o mandato de gestión para generar más confianza.",
      propertyVerificationSaveFirst:
        "Puedes publicar sin verificar. Guarda el borrador y verifica el inmueble cuando te venga bien.",
    },
    inquilinoHint: "Explora pisos y habitaciones y encuentra compañeros con los que encajar.",
    anfitrionHint:
      "Publica tu habitación, sube fotos, indica servicios y disponibilidad, y recibe solicitudes de inquilinos compatibles.",
    propietarioHint:
      "Publica tus pisos, revisa grupos formados e inquilinos en tu ciudad, y contacta antes de recibir solicitudes.",
    agenciaHint: "Gestiona la cartera de pisos de tus clientes.",
    ownerTenantsTitle: "Inquilinos y grupos",
    ownerTenantsSubtitle:
      "Grupos formados en tus ciudades, inquilinos compatibles y solicitudes recientes. Contacta antes o después de que soliciten tu piso.",
    ownerTenantsPublicHint:
      "En pisos públicos cualquier grupo puede solicitar; en privados desbloquea grupos concretos desde Mis pisos → Acceso.",
    formedGroupsTitle: "Grupos formados",
    formedGroupsSubtitle:
      "Equipos listos para alquilar juntos en las ciudades donde tienes pisos publicados.",
    noFormedGroups: "Aún no hay grupos formados en tus ciudades. Vuelve más tarde o revisa las solicitudes entrantes.",
    ownerMatchesSubtitle:
      "Inquilinos descubribles cuyo estilo de convivencia encaja contigo. Escríbeles para conocerles antes de recibir una solicitud.",
    ownerApplicationsSubtitle: "Solicitudes recientes sobre tus pisos (públicos o privados desbloqueados).",
    metrics: {
      drafts: "Borradores",
      archived: "Archivados",
      approved: "Aprobadas",
      rejected: "Rechazadas",
      totalApps: "Solicitudes totales",
      revenueEst: "Ingresos mensuales estimados",
      hosts: "Anfitriones asignados",
      clients: "Clientes activos",
      savedSpaces: "Pisos guardados",
      savedProfiles: "Perfiles guardados",
      chats: "Conversaciones",
      pendingApps: "Solicitudes pendientes",
    },
  },
  upload: {
    selectFile: "Subir imagen",
    uploading: "Subiendo…",
    remove: "Quitar",
    dropHint: "JPG, PNG o WebP (máx. 5 MB)",
    clickToUpload: "Arrastra una foto o haz clic para subir",
    orPasteUrl: "O pega una URL",
    error: "No se pudo subir la imagen.",
    coverHint: "Imagen principal del espacio. Se mostrará en las tarjetas y en el detalle.",
    avatarHint: "Foto de perfil visible para otros miembros y en tus solicitudes.",
    galleryHint: "Imágenes adicionales del espacio (opcional).",
  },
  editProfile: {
    title: "Editar perfil",
    subtitle: "Cuanto más completo esté tu perfil, mayor será tu visibilidad y tu puntuación.",
    displayName: "Nombre para mostrar",
    professionalRole: "¿A qué te dedicas? (opcional)",
    professionalRoleHint: "Solo contexto: estudiante, cuidador/a, freelance… No define tu compatibilidad.",
    bio: "Presentación breve",
    bioHint: "Cuéntanos cómo vives, qué buscas en un piso compartido y con quién te gustaría convivir (mín. 30 caracteres para puntuación máxima).",
    avatar: "Foto de perfil",
    visibleInMatches: "Aparecer en Compañeros",
    visibleHint: "Solo inquilinos pueden mostrarse para encontrar compañeros compatibles.",
    saved: "Perfil actualizado correctamente.",
    avatarRequired: "Sube una foto de perfil para continuar.",
    bioMinLength: "Escribe al menos 30 caracteres en tu presentación.",
    previewScore: "Puntuación estimada",
    searchSection: "Preferencias de búsqueda",
    searchSectionHint: "Usamos estos datos para pre-rellenar Descubrir y priorizar espacios afines.",
    preferredCity: "Ciudad",
    preferredZone: "Zona",
    cityAny: "Cualquiera",
    zoneAny: "Todas las zonas",
    cityBarcelona: "Barcelona",
    cityMadrid: "Madrid",
    cityValencia: "Valencia",
    citySevilla: "Sevilla",
    cityGranada: "Granada",
    budgetMax: "Presupuesto máximo (€/mes)",
    budgetPlaceholder: "950",
    moveIn: "Fecha de entrada deseada",
    roomType: "Tipo de habitación preferida",
    roomTypePlaceholder: "Ej. individual, doble, con baño…",
    lifestyleTags: "Etiquetas de estilo de vida",
    lifestyleTagsHint: "Elige hasta 8. Ayudan a otros miembros a conocerte de un vistazo.",
    publisherSubtitle:
      "Verificamos tu identidad y tus inmuebles para que los inquilinos confíen en ti. No hace falta rellenar hábitos de convivencia.",
    publisherBioHint:
      "Breve presentación como propietario o agencia: experiencia, zonas donde operas, tipo de inquilinos que buscas.",
    trustSection: "Confianza y verificación",
    trustSectionHint:
      "Opcional y cuando quieras. Verificar identidad e inmuebles ayuda a que los inquilinos confíen, pero no es obligatorio para empezar.",
    compatSection: "Compatibilidad de convivencia",
    compatSectionHint: "El cuestionario alimenta los porcentajes de afinidad con compañeros y anfitriones.",
    editQuiz: "Actualizar cuestionario",
    quizComplete: "Cuestionario completado",
    quizIncomplete: "Pendiente — completa el cuestionario para mejorar el matching",
    chars: "caracteres",
  },
  account: {
    dangerZone: "Zona de peligro",
    deleteAccount: "Eliminar cuenta",
    deleteAccountHint:
      "Se eliminarán de forma permanente tu perfil, anuncios, mensajes y el resto de datos vinculados a tu cuenta.",
    deleteAccountConfirm:
      "¿Eliminar tu cuenta de : moon? Esta acción no se puede deshacer.",
  },
  discover: {
    location: "Ciudad",
    zone: "Zona",
    zoneAll: "Todas las zonas",
    locationPlaceholder: "Elige ciudad y zona",
    budget: "Presupuesto",
    budgetPlaceholder: "750 € – 1.000 €",
    moveIn: "Entrada",
    moveInPlaceholder: "sep. 2026",
    allCategories: "Todos",
    emptyCategory: "No hay anuncios en esta categoría.",
    configError: "Configura .env.local con las credenciales de Supabase.",
    propertyType: "Tipo de propiedad",
    propertyTypeAll: "Todos",
    propertyTypeRoom: "Habitaciones",
    propertyTypeEntire: "Pisos enteros",
  },
  publicListings: {
    metaTitle: "alojamientos compatibles — : moon shared living",
    metaDescription:
      "Descubre habitaciones y pisos compartidos en Barcelona, Madrid, Valencia, Sevilla y Granada. Filtra por ciudad, zona, precio y compatibilidad.",
    badge: "Encuentra tu lugar ideal",
    title: "Hogares compatibles",
    titleAccent: "con personas como tú",
    subtitle:
      "Descubre habitaciones y pisos compartidos con compatibilidad real. Menos sorpresas, más convivencia.",
    filters: "Filtros",
    city: "Ciudad",
    cityAll: "Todas las ciudades",
    zone: "Zona",
    zoneAll: "Todas las zonas",
    cityBarcelona: "Barcelona",
    cityMadrid: "Madrid",
    cityValencia: "Valencia",
    citySevilla: "Sevilla",
    cityGranada: "Granada",
    price: "Precio mensual",
    priceAny: "Cualquier precio",
    priceUpTo400: "Hasta 400 €",
    price400_600: "400 € – 600 €",
    price600_800: "600 € – 800 €",
    price800_1000: "800 € – 1.000 €",
    price1000Plus: "Más de 1.000 €",
    sortBy: "Ordenar por",
    sortCompat: "Mejor compatibilidad",
    sortPriceAsc: "Precio: menor a mayor",
    sortPriceDesc: "Precio: mayor a menor",
    sortRecent: "Más recientes",
    results: "{count} hogares encontrados",
    resultsLoading: "… hogares encontrados",
    empty: "No hay hogares con estos filtros. Prueba ampliando la búsqueda.",
    compatHint:
      "Inicia sesión y completa el cuestionario para ver tu compatibilidad personalizada con cada espacio.",
    compatHintCta: "Crear cuenta gratis",
    statAvailable: "Hogares disponibles",
    statCompat: "Compatibilidad media",
    statSupport: "Soporte humano",
    statSupportValue: "24/7",
    exploreNav: "Explorar",
  },
  property: {
    startingAt: "Desde",
    available: "Disponible",
    roomType: "Tipo de habitación",
    propertyType: "Tipo de inmueble",
    about: "Sobre el espacio",
    amenities: "Servicios incluidos",
    membershipApplication: "Solicitud de membresía",
    apply: "Solicitar membresía",
    applySending: "Enviando…",
    signInToApply: "Inicia sesión para solicitar",
    viewRoommates: "Ver compañeros compatibles",
    profileCompatible: "de afinidad con tu perfil",
    notFound: "No encontramos este espacio.",
    descriptionFallback:
      "En {location}, {name} es un espacio de convivencia compartida: buscamos personas compatibles por estilo de vida, no por un perfil laboral concreto.",
    applySuccess: "Solicitud enviada. Revisa tu espacio de miembro.",
    applyDuplicate: "Ya tienes una solicitud activa para este espacio.",
    yourHost: "Tu anfitrión de convivencia",
    hostLabel: "Anfitrión del espacio",
    hostHint:
      "Vive con esta persona en el piso. La afinidad mide hábitos y estilo de convivencia, no solo el contrato.",
    compatOwnerOnly:
      "Este piso lo publica el propietario sin anfitrión asignado. La compatibilidad de convivencia se calcula cuando formas grupo con otros inquilinos o cuando el propietario asigna anfitrión.",
    compatNone: "Completa el cuestionario para ver tu afinidad con el espacio.",
    privateBadge: "Privado",
    publicBadge: "Público",
    privateHint: "Solo visible para ti y los grupos que el propietario desbloquee.",
    conditions: "Condiciones",
    trustTitle: "Confianza",
    ownerVerified: "Propietario verificado",
    propertyVerified: "Inmueble verificado",
    propertyPending: "Verificación del inmueble en curso",
    propertyNotVerified: "Inmueble sin verificar",
  },
  propertyVerification: {
    title: "Verificación del inmueble",
    subtitle:
      "Opcional. Revisamos titularidad o mandato cuando quieras; no hace falta para publicar.",
    verified: "Inmueble verificado",
    pending: "Verificación en curso",
    notVerified: "Sin verificar",
    startDemo: "Verificar inmueble (demo)",
    completeDemo: "Completar verificación demo",
    pendingHint: "Revisión simulada — pulsa completar cuando quieras cerrar el demo.",
    verifiedHint: "Los inquilinos verán el sello de inmueble verificado en tu anuncio.",
    skipHint: "Puedes publicar y editar el anuncio sin verificar. Hazlo cuando te venga bien.",
    why: "Saber que el piso existe y pertenece a quien publica reduce el riesgo para quien busca hogar.",
  },
  matches: {
    title: "Personas con las que encajarías",
    subtitle:
      "Compañeros para alquilar en grupo y anfitriones con los que convivirías en el mismo espacio.",
    empty: "Aún no hay perfiles en la comunidad.",
    demoProfile: "Perfil de demostración",
    demoChatHint: "Este perfil es de demostración. Regístrate y completa tu perfil para chatear con miembros verificados.",
    chatError: "No se pudo iniciar la conversación. Inténtalo de nuevo.",
    startChat: "Iniciar conversación",
    viewProfile: "Ver perfil",
    verifiedMembers: "Miembros verificados",
    showcaseMembers: "Perfiles destacados",
    showcaseHosts: "Anfitriones destacados",
    roommatesSection: "Compañeros de piso",
    roommatesHint: "Inquilinos compatibles para formar grupo y alquilar juntos.",
    roommateMatchLabel: "afinidad de convivencia",
    hostsSection: "Anfitriones",
    hostsHint: "Personas que gestionan espacios donde podrías vivir.",
    hostMatchLabel: "afinidad con anfitrión",
  },
  compat: {
    quizTitle: "Cuestionario de compatibilidad",
    quizSubtitleInquilino:
      "Así calculamos tu afinidad con compañeros de piso y con los anfitriones de cada espacio.",
    quizSubtitleAnfitrion:
      "Define tu estilo de convivencia para emparejarte con inquilinos que encajen en tus espacios.",
    saveQuiz: "Guardar y continuar",
    startQuiz: "Hacer cuestionario",
    quizRequiredTitle: "Completa tu cuestionario",
    quizRequiredInquilino:
      "Necesitamos tus preferencias de convivencia para mostrar compañeros y porcentajes fiables.",
    quizRequiredHost:
      "Como anfitrión, el cuestionario permite recomendar inquilinos compatibles con tu forma de gestionar el piso.",
    roleNotSupported: "Este cuestionario está disponible para inquilinos y anfitriones.",
    breakdownTitle: "Desglose de compatibilidad",
    tapForBreakdown: "Ver desglose de compatibilidad",
    hostMatchesTitle: "Inquilinos compatibles",
    hostMatchesSubtitle:
      "Inquilinos cuyo estilo de convivencia encaja con el tuyo para tu habitación.",
    noHostMatches: "No hay inquilinos descubribles con tu configuración actual.",
  },
  messages: {
    title: "Mensajes",
    empty: "Aún no tienes conversaciones",
    emptyHint: "Inicia una conversación desde Compañeros para dar el siguiente paso.",
    browseMatches: "Ver compañeros",
    placeholder: "Escribe un mensaje…",
    send: "Enviar",
    you: "Tú",
    signInRequired: "Inicia sesión para ver tus mensajes.",
    selectConversation: "Selecciona una conversación",
    newMessage: "Nuevo mensaje",
  },
  profile: {
    portal: "Espacio de miembro",
    welcome: "Bienvenido a casa",
    progress: "Vas completando tu perfil para encontrar hogar y compañeros afines ({score} %).",
    editProfile: "Editar perfil",
    roleTitle: "Título o rol profesional",
    bio: "Bio de convivencia",
    discoverable: "Aparecer en búsqueda de compañeros",
    applications: "Solicitudes activas",
    inProgress: "en curso",
    noApplications: "No tienes solicitudes activas.",
    profileScore: "Puntuación de perfil",
    scoreHint: "Completa tu perfil para alcanzar el 100 % de visibilidad.",
    completeProfile: "Completar perfil",
    compatibilityQuiz: "Cuestionario de compatibilidad",
    compatibilityQuizHint: "Mejora los porcentajes de afinidad con compañeros y anfitriones.",
    signInTitle: "Espacio de miembro",
    signInHint: "Inicia sesión para ver tus solicitudes y tu puntuación de perfil.",
    memberFallback: "Miembro",
    hostPortal: "Panel de anfitrión",
    hostWelcome: "Publica y gestiona tus habitaciones",
    hostProgress:
      "Completa el cuestionario, sube fotos de tu habitación y revisa solicitudes ({score} %).",
    incomingApplications: "Solicitudes en tus habitaciones",
    noIncomingApplications: "Aún no hay solicitudes en tus habitaciones publicadas.",
    goToPanel: "Ir al panel",
    goToSpaces: "Ver mis pisos",
    goToMyRooms: "Mis habitaciones",
    goToConvivencia: "Convivencia y compatibles",
    ownerPortal: "Panel de propietario",
    publishSpace: "Publicar piso",
    publishRoom: "Publicar habitación",
    myGroups: "Mis grupos de convivencia",
    identitySection: "Confianza en tu perfil",
    identityNudge:
      "Verificar tu identidad es opcional y ayuda a que otros confíen en ti. Puedes hacerlo cuando quieras.",
    identityNudgeCta: "Verificar identidad",
  },
  access: {
    welcomeBack: "Bienvenido de nuevo",
    signInSubtitle: "Accede a tu espacio de miembro",
    createAccount: "Crear cuenta",
    joinSubtitle: "Únete a la comunidad : moon",
    tagline:
      "Comparte vivienda con personas compatibles. Menos gasto, más apoyo y un hogar donde encajar — empezamos por Barcelona y también Madrid, Valencia, Sevilla y Granada.",
    orEmail: "O continúa con el correo",
    continueGoogle: "Continuar con Google",
    continueFacebook: "Continuar con Facebook",
    oauthError: "No se pudo completar el inicio con la red social. Inténtalo de nuevo.",
    oauthRoleRequired: "Selecciona tu rol antes de registrarte con Google o Facebook.",
    oauthOpening: "Abriendo…",
    propertySignupHint:
      "Crea tu cuenta gratis; después del onboarding volverás a este espacio para solicitarlo.",
    signUp: "Registrarse",
    notMember: "¿Aún no eres miembro?",
    hasAccount: "¿Ya tienes cuenta?",
    createAccountLink: "Crear cuenta",
    signInLink: "Iniciar sesión",
    confirmEmail: "Revisa tu correo para confirmar la cuenta (si la verificación está activa en Supabase).",
    confirmEmailTitle: "Cuenta creada",
    roleRequired: "Selecciona tu rol en la plataforma (inquilino, anfitrión, propietario o agencia).",
    accountRoleHint: "Define qué puedes hacer en : moon: buscar espacio, gestionar convivencia, publicar inmuebles o actuar como agencia.",
    completeRoleTitle: "Completa tu perfil",
    continue: "Continuar",
    showPassword: "Mostrar contraseña",
    hidePassword: "Ocultar contraseña",
    forgotTitle: "Recuperar contraseña",
    forgotSubtitle: "Te enviaremos un enlace al correo para restablecerla.",
    forgotSubmit: "Enviar enlace",
    forgotSent: "Si existe una cuenta con ese correo, recibirás las instrucciones en breve.",
    signupConsent:
      "Acepto la política de privacidad y los términos de uso de : moon shared living.",
    signupConsentRequired: "Debes aceptar la política de privacidad y los términos para registrarte.",
  },
  applicationStatus: {
    draft: "Borrador",
    submitted: "Enviada",
    interview_scheduled: "Entrevista programada",
    final_review: "Revisión final",
    approved: "Aprobada",
    rejected: "Rechazada",
  },
  public: {
    heroBadge: "Alquilar hogar, no solo una habitación",
    heroLine1: "Elige con quién vives,",
    heroLine2: "no solo dónde.",
    heroLine3: "Vive acompañado.",
    heroSubtitle:
      "Para estudiantes, expats, separados o cualquiera que comparta piso, : moon conecta personas compatibles para alquilar juntos, convivir mejor y sentir hogar desde el primer día — en 5 ciudades universitarias.",
    heroTrust: [
      "Matching por hábitos, valores y ritmo de vida",
      "Grupos para alquilar piso entero con reparto justo",
      "Verificación de identidad y perfiles de anfitrión visibles",
    ],
    ctaStart: "Empezar gratis",
    ctaStartFree: "Crear cuenta gratis",
    ctaFindMatches: "Buscar compañeros",
    howItWorks: "Cómo funciona",
    howItWorksTitle: "Cómo funciona : moon",
    howItWorksIntro:
      "Inspirados en la visión de convivencia consciente: con quién vives importa tanto como el piso. Forma grupo, conoce al anfitrión y alinea expectativas antes de mudarte.",
    pillarsTitle: "¿Por qué : moon?",
    pillar1Title: "Compatibilidad real",
    pillar1Text:
      "Cuestionario de estilo de vida. Afinidad con compañeros, anfitriones y espacios — con desglose claro al pulsar el porcentaje.",
    pillar2Title: "Grupos que alquilan juntos",
    pillar2Text:
      "Forma equipo, reparte el alquiler con transparencia y presentaos mejor al propietario. Los pisos privados se desbloquean grupo a grupo.",
    pillar3Title: "Identidad y confianza",
    pillar3Text:
      "Verificación de identidad (demo Veriff), perfiles completos y mensajes antes de dar el paso — menos sorpresas, más hogar.",
    groupsTitle: "Alquilar en grupo, sin caos",
    groupsIntro:
      "Alquilar juntos falla sin herramientas: no sabes con quién vives, no repartís bien y el propietario no confía. : moon ordena ese proceso.",
    groupsStep1: "Crea o únete a un grupo compatible",
    groupsStep2: "Repartid el alquiler con pesos por habitación",
    groupsStep3: "Solicitad pisos públicos o privados desbloqueados",
    audiencesTitle: "Para quién es : moon",
    audiences: [
      "Estudiantes que buscan piso y compañeros afines",
      "Expats que llegan sin red local",
      "Personas separadas o divorciadas que reinician hogar",
      "Profesionales que quieren convivencia tranquila, no solo dividir gastos",
    ],
    rolesTitle: "Unimos generaciones y oportunidades",
    rolesIntro:
      "Creamos puentes entre quienes buscan un hogar, quienes ceden habitación y quienes quieren gestionar su vivienda con tranquilidad.",
    ctaBlockTitle: "Tu próximo hogar te espera",
    ctaBlockSubtitle:
      "Únete a la plataforma que pone la afinidad en el centro de la vivienda compartida. Registro gratuito en esta fase.",
    footerTagline: "Vivienda compartida con compatibilidad, en España.",
    freePhase: "Fase beta gratuita — sin monetización activa",
    step1Title: "Perfil + identidad",
    step1Text:
      "Cuéntanos tu estilo de vida y verifica tu identidad (demo). Estudiante, expat o en transición: tu historia importa.",
    step2Title: "Compañeros, grupos y espacios",
    step2Text:
      "Encuentra flatmates, forma grupo para alquilar entero y descubre pisos con anfitrión — o entiende cuándo la afinidad llega al formar grupo.",
    step3Title: "Convive con confianza",
    step3Text:
      "Habla con anfitriones, reparte el alquiler en grupo y solicita el hogar cuando todos estéis alineados.",
    notInsurance:
      "Contratos digitales, seguros y acompañamiento 24/7 forman parte de la hoja de ruta; en esta fase beta no están activos en la app.",
    hosts: "Anfitriones",
    owners: "Propietarios",
    agencies: "Agencias",
    landing: {
      badge: "España · 5 ciudades",
      heroLine1: "Elige con quién vives,",
      heroLine2: "no solo dónde.",
      heroSubtitle: "Comparte piso con personas compatibles por hábitos, valores y ritmo de vida.",
      heroAudience: "Estudiantes, expats, profesionales.",
      statCompat: "Compatibilidad media",
      statVerified: "Identidad verificada",
      statSupport: "Soporte humano",
      ctaStartFree: "Crear cuenta gratis",
      howItWorks: "Cómo funciona",
      ctaExplore: "Explorar sin registrarme",
      pillarsTitle: "Por qué : moon",
      pillarsSubtitle: "Vivir acompañado, sin sorpresas",
      pillar1Title: "Compatibilidad real",
      pillar1Text: "Cuestionario de hábitos y valores. Afinidad con compañeros, anfitriones y espacios — con desglose claro.",
      pillar2Title: "Grupos que alquilan juntos",
      pillar2Text: "Forma equipo, reparte el alquiler con transparencia y presentaos mejor al propietario.",
      pillar3Title: "Identidad verificada",
      pillar3Text: "Verificación de identidad, perfiles completos y mensajes antes de dar el paso.",
      stepsTitle: "4 pasos hacia tu nuevo hogar",
      stepsGuide: "Ver guía completa para inquilinos",
      step1Title: "Crea tu perfil",
      step1Text: "Cuéntanos tu estilo de vida, rutinas y preferencias de convivencia.",
      step2Title: "Descubre espacios",
      step2Text: "Explora pisos con tu afinidad para las personas que ya viven allí.",
      step3Title: "Conecta",
      step3Text: "Chatea con anfitriones y envía solicitudes a los lugares que te gusten.",
      step4Title: "Múdate",
      step4Text: "Firma tu contrato digital y convive con compañeros compatibles.",
      communityWait: "Tu comunidad te espera",
      startNow: "Empezar ahora",
      rolesTitle: "¿Cómo usas : moon?",
      rolesSubtitle: "Distintos roles, misma misión: convivencia mejor",
      roleTenantDesc: "Busco piso y compañeros compatibles",
      roleHostDesc: "Gestiono convivencia en mi piso",
      roleOwnerDesc: "Publico y administro mis pisos",
      roleAgencyDesc: "Opero la cartera de mis clientes",
      ctaBlockTitle: "Tu próximo hogar te espera",
      ctaBlockSubtitle: "Crea tu perfil, explora espacios compatibles y da el paso con confianza.",
    },
    howItWorksPage: {
      eyebrow: "Guía por rol",
      title: "cómo funciona : moon",
      forRoleLabel: "Para {role}",
      viewRoleLanding: "Ver landing de {role}",
      knowAgencyFlow: "Conocer flujo para agencias →",
      roles: {
        inquilino: "Inquilino",
        inquilinos: "Inquilinos",
        anfitrion: "Anfitrión",
        anfitriones: "Anfitriones",
        propietario: "Propietario",
        propietarios: "Propietarios",
        agencia: "Agencia",
        agencias: "Agencias",
      },
      ctaLabels: {
        inquilino: "Crear cuenta como inquilino",
        anfitrion: "Registrarme como anfitrión",
        propietario: "Registrarme como propietario",
        agencia: "Registrar agencia",
      },
      subtitle: "Misma plataforma, distintos caminos: elige tu rol y sigue los pasos. Compatibilidad, grupos e identidad verificada en el centro de cada flujo.",
      pillar1Title: "Compatibilidad real",
      pillar1Text: "Cuestionario de estilo de vida con desglose claro de afinidad entre personas y espacios.",
      pillar2Title: "Grupos que alquilan juntos",
      pillar2Text: "Formad equipo, repartid el alquiler y desbloquead pisos privados cuando encajáis.",
      pillar3Title: "Identidad y confianza",
      pillar3Text: "Verificación demo, perfiles completos y mensajes antes de dar el paso.",
      exploreListings: "Explorar alojamientos sin cuenta",
      betaNote: ": moon no es un seguro ni un servicio de mediación legal. fase beta gratuita — sin monetización activa.",
      inquilino: {
        headline: "Encuentra hogar y compañeros que encajan",
        intro: "Para estudiantes, expats, profesionales o quien reinicia etapa: perfil de convivencia, grupos para alquilar entero y habitaciones con anfitrión visible.",
        step1Title: "Perfil y cuestionario",
        step1Text: "Cuéntanos rutinas, hábitos y preferencias. Verifica tu identidad (demo) para generar confianza desde el primer contacto.",
        step2Title: "Grupo o búsqueda individual",
        step2Text: "Forma equipo para alquilar un piso entero con reparto transparente, o busca habitación en pisos ya habitados.",
        step3Title: "Descubre con afinidad",
        step3Text: "Explora alojamientos públicos en Barcelona, Madrid, Valencia, Sevilla y Granada. Filtra por ciudad y zona.",
        step4Title: "Conecta y solicita",
        step4Text: "Chatea, revisa perfiles completos y envía solicitudes solo donde la afinidad tiene sentido.",
        step5Title: "Múdate con claridad",
        step5Text: "Entra sabiendo qué esperar: reglas de convivencia, personas implicadas y expectativas alineadas antes de firmar.",
        extrasTitle: "Alquilar en grupo, sin caos",
        extra1: "Crea o únete a un grupo compatible por estilo de vida",
        extra2: "Repartid el alquiler con pesos por habitación",
        extra3: "Solicitad pisos públicos o privados desbloqueados para vuestro grupo",
      },
      anfitrion: {
        headline: "Gestiona convivencia en tu piso",
        intro: "Vives en el piso y quieres compañeros afines: publica tu habitación, define cómo convives y elige solicitantes con datos, no solo intuición.",
        step1Title: "Perfil de anfitrión",
        step1Text: "Presenta quién eres, tu rol en el piso y qué tipo de convivencia buscas.",
        step2Title: "Cuestionario de convivencia",
        step2Text: "Horarios, limpieza, visitas, ruido… : moon traduce tus respuestas en señales de compatibilidad.",
        step3Title: "Publica tu espacio",
        step3Text: "Fotos, habitación disponible, reglas de casa y amenities. Tu listing es la carta de presentación del piso.",
        step4Title: "Recibe solicitudes filtradas",
        step4Text: "Candidatos ordenados por afinidad. Menos mensajes irrelevantes, más conversaciones con sentido.",
        step5Title: "Elige y convive mejor",
        step5Text: "Conoce perfiles, chatea y acepta cuando encaja. Menos rotación, menos fricción diaria.",
      },
      propietario: {
        headline: "Tu cartera, grupos pre-validados",
        intro: "Tienes uno o varios pisos compartidos: publica inmuebles, asigna anfitriones y recibe solicitudes de grupos e inquilinos ya filtrados por compatibilidad.",
        step1Title: "Alta y verificación",
        step1Text: "Cuenta de propietario con identidad verificada (demo). Base de confianza para inquilinos y agencias.",
        step2Title: "Registra propiedades",
        step2Text: "Añade pisos, habitaciones, condiciones y documentación. Define si el listing es público o privado.",
        step3Title: "Asigna anfitriones",
        step3Text: "Vincula a la persona que vive en el piso y gestiona el día a día de la convivencia.",
        step4Title: "Recibe grupos cualificados",
        step4Text: "Solicitudes con desglose de compatibilidad del grupo. Menos sorpresas, menos rotación.",
        step5Title: "Supervisa con tranquilidad",
        step5Text: "Panel con estado de cada inmueble, solicitudes pendientes e historial de convivencia.",
        extrasTitle: "¿Gestionas muchos pisos?",
        extra1: "Las agencias pueden operar tu cartera desde un panel multi-cliente",
        extra2: "Mismos filtros de compatibilidad y anfitriones asignados por inmueble",
        agenciesLink: "Conocer flujo para agencias →",
      },
      agencia: {
        headline: "Opera carteras de convivencia compartida",
        intro: "Para inmobiliarias y gestores profesionales: publica en nombre de propietarios, asigna anfitriones y entrega informes claros por piso y por cliente.",
        step1Title: "Cuenta agencia",
        step1Text: "Alta con perfil profesional. Invita al equipo y organiza propietarios bajo tu cartera.",
        step2Title: "Publica por cliente",
        step2Text: "Listings vinculados al propietario correcto: fotos, condiciones, visibilidad pública o privada.",
        step3Title: "Anfitriones por piso",
        step3Text: "Asigna referentes de convivencia en cada inmueble para filtrar candidatos en el terreno.",
        step4Title: "Solicitudes con afinidad",
        step4Text: "Grupos e inquilinos llegan con score de compatibilidad. Prioriza entradas estables.",
        step5Title: "Informes y retención",
        step5Text: "Métricas por inmueble y propietario: menos incidencias, más satisfacción de cartera.",
      },
    },
    hostLanding: {
      badge: "Para anfitriones",
      heroLine1: "Gestiona tu piso con",
      heroLine2: "personas que encajan.",
      heroSubtitle: "Publica tu habitación, indica tu estilo de convivencia y recibe solicitudes de inquilinos compatibles.",
      heroAudience: "Menos rotación, más tranquilidad.",
      stat1: "Menos conflictos",
      stat2: "Permanencia media",
      stat3: "Soporte humano",
      stat3Value: "87%",
      stat4Value: "2.5×",
      ctaMain: "Ser anfitrión",
      ctaSecondary: "Cómo funciona",
      benefitsTitle: "Ventajas para anfitriones",
      benefitsSubtitle: "Convivencia sin estrés",
      benefit1Title: "Filtra por compatibilidad",
      benefit1Text: "El cuestionario de hábitos asegura que los solicitantes encajen con tu estilo de vida.",
      benefit2Title: "Conoce antes de aceptar",
      benefit2Text: "Chatea con candidatos, revisa sus perfiles completos y toma decisiones informadas.",
      benefit3Title: "Menos rotación",
      benefit3Text: "Las buenas elecciones de convivencia significan inquilinos que se quedan más tiempo.",
      benefit4Title: "Apoyo humano",
      benefit4Text: "El equipo : moon te acompaña en momentos de duda sobre convivencia.",
      processTitle: "Proceso",
      processSubtitle: "Tu camino al anfitrión",
      step1Title: "Crea tu perfil",
      step1Text: "Define tu estilo como anfitrión.",
      step2Title: "Cuestionario",
      step2Text: "Completa el de convivencia.",
      step3Title: "Publica",
      step3Text: "Sube fotos y detalles.",
      step4Title: "Elige",
      step4Text: "Revisa solicitudes compatibles.",
      processGuide: "Ver guía paso a paso",
      finalCtaTitle: "Comparte tu espacio",
      finalCtaSubtitle: "con tranquilidad",
      finalCtaText: "Publica tu habitación, filtra por compatibilidad y gestiona la convivencia con apoyo humano.",
      finalCtaButton: "Ser anfitrión gratis",
    },
    ownerLanding: {
      badge: "Para propietarios",
      heroLine1: "Tu cartera de pisos",
      heroLine2: "grupos pre-validados",
      heroSubtitle: "Publica tus inmuebles, asigna anfitriones y recibe solicitudes de grupos e inquilinos ya filtrados por compatibilidad.",
      heroAudience: "Menos rotación, más tranquilidad.",
      stat1: "Identidad verificada",
      stat2: "Compatibilidad grupal",
      stat3: "Soporte humano",
      stat3Value: "100%",
      stat4Value: "Score",
      ctaMain: "Soy propietario",
      ctaSecondary: "Cómo funciona",
      benefitsTitle: "Ventajas para propietarios",
      benefitsSubtitle: "Control y visibilidad total",
      benefit1Title: "Grupos pre-validados",
      benefit1Text: "Las solicitudes llegan con desglose de compatibilidad del grupo completo.",
      benefit2Title: "Anfitriones asignados",
      benefit2Text: "Vincula a quien vive en cada piso para filtrar candidatos en el terreno.",
      benefit3Title: "Visibilidad pública o privada",
      benefit3Text: "Elige qué pisos son visibles para todos y cuáles requieren desbloqueo.",
      benefit4Title: "Panel de gestión",
      benefit4Text: "Estado de cada inmueble, solicitudes pendientes e historial de convivencia.",
      processTitle: "Proceso",
      processSubtitle: "Tu camino como propietario",
      step1Title: "Alta y verificación",
      step1Text: "Crea tu cuenta y verifica tu identidad.",
      step2Title: "Registra propiedades",
      step2Text: "Añade pisos, habitaciones y condiciones.",
      step3Title: "Asigna anfitriones",
      step3Text: "Vincula referentes de convivencia.",
      step4Title: "Recibe solicitudes",
      step4Text: "Grupos e inquilinos compatibles.",
      processGuide: "Ver guía paso a paso",
      agenciesBoxTitle: "¿Gestionas muchos pisos?",
      agenciesBoxText: "Las agencias pueden operar tu cartera desde un panel multi-cliente con los mismos filtros de compatibilidad.",
      agenciesLink: "Ver flujo para agencias →",
      finalCtaTitle: "Tus pisos,",
      finalCtaSubtitle: "mejores inquilinos",
      finalCtaText: "Publica tus inmuebles, recibe grupos pre-validados y reduce la rotación con compatibilidad real.",
      finalCtaButton: "Registrarme como propietario",
    },
    agencyLanding: {
      badge: "Para agencias",
      heroLine1: "Opera carteras de",
      heroLine2: "convivencia compartida",
      heroSubtitle: "Gestiona los pisos de tus clientes, asigna anfitriones y entrega informes claros por inmueble y por propietario.",
      heroAudience: "Panel multi-cliente profesional",
      stat1: "Panel centralizado",
      stat2: "Anfitriones por piso",
      stat3: "Soporte dedicado",
      stat3Value: "Multi-cliente",
      stat4Value: "Asignados",
      ctaMain: "Registrar agencia",
      ctaSecondary: "Cómo funciona",
      benefitsTitle: "Ventajas para agencias",
      benefitsSubtitle: "Gestión profesional",
      benefit1Title: "Panel multi-cliente",
      benefit1Text: "Organiza propietarios bajo tu cartera y gestiona todos los pisos desde un solo lugar.",
      benefit2Title: "Publica en nombre del propietario",
      benefit2Text: "Cada listing vinculado al cliente correcto con visibilidad pública o privada.",
      benefit3Title: "Anfitriones asignados",
      benefit3Text: "Referentes de convivencia en cada inmueble para filtrar candidatos.",
      benefit4Title: "Informes por cliente",
      benefit4Text: "Métricas de incidencias, satisfacción y retención por propietario.",
      processTitle: "Proceso",
      processSubtitle: "Tu camino como agencia",
      step1Title: "Cuenta agencia",
      step1Text: "Alta con perfil profesional e invita al equipo.",
      step2Title: "Añade propietarios",
      step2Text: "Organiza a tus clientes bajo tu cartera.",
      step3Title: "Publica pisos",
      step3Text: "Fotos, condiciones y visibilidad por cliente.",
      step4Title: "Gestiona solicitudes",
      step4Text: "Grupos compatibles por inmueble.",
      processGuide: "Ver guía paso a paso",
      finalCtaTitle: "Tu cartera,",
      finalCtaSubtitle: "optimizada",
      finalCtaText: "Gestiona múltiples propietarios, asigna anfitriones y reduce incidencias con matching real.",
      finalCtaButton: "Crear cuenta de agencia",
    },
  },
  onboarding: {
    basicsTitle: "Cuéntanos quién eres",
    basicsSubtitle:
      "Nombre completo y edad nos ayudan a personalizar compatibilidad y cumplir requisitos de convivencia.",
    fullName: "Nombre completo",
    fullNamePlaceholder: "Ej. María García López",
    birthDate: "Fecha de nacimiento",
    ageHint: "Debes tener al menos 18 años para usar : moon.",
    ageInvalid: "La edad debe estar entre 18 y 99 años.",
    nameRequired: "Indica tu nombre completo.",
    birthRequired: "Indica tu fecha de nacimiento.",
    saveAndContinue: "Guardar y continuar",
    welcomeTitle: "Bienvenido a : moon",
    welcomeBody:
      "En unos minutos dejarás listo tu perfil para que el matching funcione de verdad.",
    quizTitle: "Tu perfil de convivencia",
    quizBody:
      "El cuestionario alimenta los porcentajes de compatibilidad con compañeros y anfitriones.",
    profileTitle: "Tu presentación",
    profileBody: "Foto y bio de convivencia: cuanto más honesto sea tu perfil, mejor será el matching.",
    progress: "Paso {current} de {total}",
    continue: "Continuar",
    finish: "Ir a mi espacio",
    point1: "Matching por hábitos y valores, no solo por precio",
    point2: "Barcelona, Madrid, Valencia, Sevilla y Granada",
    point3: "Gratis durante el primer año",
    goQuiz: "Hacer cuestionario ahora",
    goProfile: "Completar perfil",
  },
  member: {
    notFound: "No encontramos este perfil.",
    about: "Sobre esta persona",
    lifestyle: "Estilo de convivencia",
    groups: "Grupos de alquiler",
    hostSpaces: "Espacios que gestiona",
    ownerSpaces: "Pisos publicados",
    allSpaces: "Propiedades",
    verifiedHint: "Identidad verificada — más confianza para convivir.",
    trustHint:
      "Propietario o agencia verificado. Cada anuncio puede mostrar además verificación del inmueble.",
  },
  identity: {
    title: "Verificación de identidad",
    subtitle:
      "Opcional. Verificamos quién eres para generar confianza; puedes hacerlo ahora o más tarde desde tu perfil.",
    verified: "Identidad verificada",
    pending: "Verificación en curso",
    notVerified: "Sin verificar",
    startDemo: "Verificar ahora (demo)",
    completeDemo: "Completar verificación demo",
    pendingHint: "Revisión simulada — pulsa completar cuando quieras cerrar el demo.",
    verifiedHint: "Tu perfil muestra el sello de confianza en matching y mensajes.",
    skipHint: "No hace falta ahora. Puedes publicar, explorar y verificar cuando quieras.",
    why: "Estudiantes, expats y personas en transición merecen convivir con seguridad, no solo alquilar una habitación.",
    ownerWhy:
      "Verificar tu identidad ayuda a los inquilinos a confiar en quien publica el piso. Puedes hacerlo cuando te venga bien.",
  },
  groups: {
    title: "Grupos para alquilar juntos",
    subtitle:
      "Forma equipo con personas compatibles, reparte el alquiler con claridad y desbloquea pisos privados del propietario.",
    myGroups: "Mis grupos",
    create: "Crear grupo",
    createTitle: "Nuevo grupo de convivencia",
    name: "Nombre del grupo",
    city: "Ciudad objetivo",
    targetMembers: "Personas en el grupo",
    notes: "Notas (opcional)",
    empty: "Aún no formas parte de ningún grupo.",
    emptyHint: "Invita compañeros desde Matches o crea un grupo para alquilar un piso entero.",
    members: "miembros",
    fairSplit: "Reparto justo del alquiler",
    fairSplitHint:
      "Cada habitación puede tener un peso distinto. Así evitáis discusiones antes de mudaros — como en : moon.",
    totalRent: "Alquiler total del piso",
    markReady: "Marcar grupo listo",
    status: {
      forming: "Formándose",
      ready: "Listo para solicitar",
      active: "Activo",
      archived: "Archivado",
    },
    lead: "Coordinador",
    member: "Miembro",
    viewGroup: "Ver grupo",
    unlockTitle: "Desbloquear piso privado",
    unlockHint: "El propietario elige qué grupos pueden ver y solicitar espacios privados.",
    grantAccess: "Desbloquear para este grupo",
    accessGranted: "Grupo desbloqueado",
    noAccess: "Nadie desbloqueado aún.",
    requestJoin: "Solicitar unirme",
    requestPending: "Solicitud enviada",
    pendingRequests: "Solicitudes pendientes",
    accept: "Aceptar",
    deny: "Denegar",
    groupFormed: "Grupo formado — listo para solicitar pisos",
    shareGroup: "Compartir grupo",
    shareCreated: "¡Grupo creado! Compártelo con tus compañeros",
    copyLink: "Copiar enlace",
    shareWhatsApp: "WhatsApp",
    shareEmail: "Email",
    linkCopied: "Enlace copiado",
    inviteTitle: "Te invitan a un grupo",
    inviteSubtitle: "Únete para alquilar juntos en : moon",
    inviteJoin: "Unirme al grupo",
    inviteSignUp: "Crear cuenta y unirme",
    spotsLeft: "plazas libres",
    formedBadge: "Grupo formado",
  },
  referrals: {
    title: "Invita amigos",
    subtitle: "Invita a 5 amigos y vive un año gratis",
    progress: "amigos registrados",
    goalReached: "¡Meta conseguida! Te contactaremos con tu recompensa.",
    yourLink: "Tu enlace de invitación",
    copyLink: "Copiar enlace",
    share: "Compartir",
    linkCopied: "Enlace copiado",
    loadError: "No pudimos cargar tu enlace de referidos. Inténtalo más tarde.",
  },
  expenses: {
    title: "Gastos del piso",
    subtitle: "Registra gastos compartidos y consulta quién debe a quién.",
    addExpense: "Añadir gasto",
    label: "Concepto",
    amount: "Importe (€)",
    category: "Categoría",
    splitMode: "Reparto",
    splitProportional: "Proporcional por habitación",
    splitEqual: "A partes iguales",
    date: "Fecha",
    balances: "Saldos",
    paid: "Pagado",
    owes: "Debe",
    netPositive: "le deben",
    netNegative: "debe",
    settled: "Liquidado",
    recordSettlement: "Registrar pago",
    from: "De",
    to: "Para",
    noExpenses: "Aún no hay gastos registrados.",
    delete: "Eliminar",
    openManager: "Gestionar gastos",
    tabSummary: "Resumen",
    tabHistory: "Historial",
    tabAdd: "Añadir",
    totalMonth: "Gastado este mes",
    yourBalance: "Tu saldo",
    allSettled: "Estáis al día",
    suggestedPayments: "Pagos sugeridos",
    paysTo: "paga a",
    splitPreview: "Vista previa del reparto",
    confirmDelete: "¿Eliminar este gasto?",
    cancel: "Cancelar",
    saveExpense: "Guardar gasto",
    pullRefresh: "Actualizar",
    paidByYou: "Pagado por ti",
    memberShare: "Tu parte",
    categories: {
      rent: "Alquiler",
      utilities: "Suministros",
      internet: "Internet",
      cleaning: "Limpieza",
      groceries: "Compras",
      repair: "Reparación",
      other: "Otros",
    },
  },
  leases: {
    title: "Mi contrato",
    noLeases: "Aún no tienes contratos.",
    status: {
      draft: "Borrador",
      pending_signatures: "Pendiente de firma",
      active: "Activo",
      ended: "Finalizado",
      cancelled: "Cancelado",
    },
    generate: "Generar contrato",
    generateSuccess: "Contrato creado. Pendiente de firma.",
    signPending: "Pendiente de tu firma",
    signed: "Firmado",
    viewListing: "Ver espacio",
  },
  application: {
    notFound: "Solicitud no encontrada.",
    progressTitle: "Progreso de tu solicitud",
    viewListing: "Ver espacio",
    nextStepsHint:
      "El anfitrión o propietario revisará tu solicitud. Te avisaremos cuando haya novedades.",
    applyAsGroup: "Solicitar como grupo",
    selectGroup: "Selecciona tu grupo formado",
    applySolo: "Solicitar solo/a",
  },
  accountRoles: {
    inquilino: "Inquilino",
    anfitrion: "Anfitrión",
    propietario: "Propietario",
    agencia: "Agencia",
  },
  legal: {
    privacy: "Privacidad",
    terms: "Términos",
    notice: "Aviso legal",
    updated: "Última actualización",
    notFound: "No encontramos este documento legal.",
  },
  blog: {
    nav: "Blog",
    title: "blog : moon shared living",
    subtitle: "Consejos y reflexiones sobre compartir piso, afinidad y vivienda en España.",
    empty: "Pronto publicaremos más artículos.",
    notFound: "Artículo no encontrado.",
    backToList: "Volver al blog",
  },
  community: {
    title: "Comunidad",
    subtitle: "Encuentros para conocer gente afín y hablar de convivencia en nuestras ciudades.",
    allCities: "Todas",
    empty: "No hay eventos próximos con estos filtros.",
    eventNotFound: "Evento no encontrado.",
    backToEvents: "Volver a eventos",
    tipsTitle: "Buenas prácticas",
    tips: [
      "Completa el cuestionario antes de ir a un encuentro.",
      "Respeta horarios y normas del espacio anfitrión.",
      "Usa los mensajes de la app para coordinar logística.",
    ],
    maxAttendees: "Plazas",
    rsvpHint: "Confirma asistencia escribiendo al equipo o a tu anfitrión por mensajes.",
    contactOrganizer: "Ir a mensajes",
    signInCta: "Inicia sesión para ver todos los eventos de la comunidad.",
  },
  admin: {
    title: "administración : moon shared living",
    backToApp: "Volver a la app",
    nav: {
      short: "Admin",
      dashboard: "Resumen",
      users: "Usuarios",
      listings: "Espacios",
      reports: "Reportes",
      settings: "Configuración",
    },
    dashboardTitle: "Panel de administración",
    dashboardSubtitle: "Moderación, contenido y métricas de la beta.",
    betaNote:
      "Para conceder acceso admin: en Supabase, marca is_admin = true en habitus_profiles del usuario.",
    stats: {
      users: "Usuarios",
      listingsPublished: "Espacios publicados",
      listingsDraft: "Borradores",
      openReports: "Reportes abiertos",
      blogPosts: "Artículos publicados",
      upcomingEvents: "Eventos próximos",
      moonAccessProgress: "Progreso Moon Access",
    },
    moonAccess: {
      title: "Moon Access (interno)",
      userCount: "Usuarios registrados",
      threshold: "Umbral activación",
      ready: "Listo para activar",
      notReady: "Aún no alcanzado",
      enabled: "Backend activo",
      showPricing: "Mostrar pricing (no activar aún)",
      note: "Stripe y Veriff se integrarán más adelante. Sin UI pública de pricing.",
    },
    usersTitle: "Usuarios",
    usersSubtitle: "Visibilidad, permisos de administrador y verificación de identidad.",
    listingsTitle: "Control de espacios",
    listingsSubtitle:
      "Asigna anfitriones a pisos, aprueba verificaciones de inmueble y modera publicaciones.",
    reportsTitle: "Reportes",
    reportsSubtitle: "Denuncias de perfiles, espacios o mensajes.",
    reportsEmpty: "No hay reportes pendientes.",
    settingsTitle: "Configuración",
    settingsSubtitle: "Parámetros de la fase beta (solo lectura en UI).",
    settingsPhase: "Fase del producto",
    settingsCities: "Ciudades activas",
    settingsContent: "Contenido editorial",
    settingsContentHint:
      "Blog y eventos se gestionan en las tablas habitus_blog_posts y habitus_community_events.",
    table: {
      name: "Nombre",
      role: "Rol",
      score: "Perfil",
      discoverable: "Visible",
      admin: "Admin",
      identity: "Identidad",
    },
    yes: "Sí",
    no: "No",
    grantAdmin: "Hacer admin",
    revokeAdmin: "Quitar admin",
    archive: "Archivar",
    noHost: "Sin anfitrión",
    assignHost: "Asignar anfitrión",
    removeHost: "Quitar anfitrión",
    verifyIdentity: "Verificar identidad",
    revokeIdentity: "Quitar verificación",
    verifyProperty: "Verificar inmueble",
    revokeProperty: "Quitar verificación inmueble",
    tableListings: {
      owner: "Propietario",
      host: "Anfitrión",
      category: "Tipo",
      propertyVerification: "Inmueble",
      actions: "Acciones",
    },
    filters: {
      searchListings: "Buscar por nombre, ciudad o propietario…",
      searchUsers: "Buscar por nombre…",
      city: "Ciudad",
      allCities: "Todas",
      zone: "Zona",
      allZones: "Todas las zonas",
      status: "Estado",
      allStatuses: "Todos",
      category: "Tipo",
      allCategories: "Todos",
      verification: "Verificación",
      allVerification: "Todas",
      role: "Rol",
      allRoles: "Todos",
      reportStatus: "Estado del reporte",
      clear: "Limpiar filtros",
      noResults: "Ningún resultado con estos filtros.",
    },
    bulk: {
      selectAll: "Seleccionar filtrados",
      deselectAll: "Deseleccionar",
      selected: "seleccionados",
      publish: "Publicar",
      archive: "Archivar",
      verifyProperty: "Verificar inmueble",
      verifyIdentity: "Verificar identidad",
      makeVisible: "Hacer visibles",
      makeHidden: "Ocultar",
      resolve: "Resolver",
      dismiss: "Descartar",
      review: "En revisión",
    },
    reportStatus: {
      open: "Abierto",
      reviewing: "En revisión",
      resolved: "Resuelto",
      dismissed: "Descartado",
    },
    import: {
      downloadExample: "Descargar CSV de ejemplo",
      chooseFile: "Elegir CSV",
      runImport: "Importar",
      rows: "filas",
      columns: "Columnas requeridas",
      invalidFile: "El archivo CSV está vacío o no es válido.",
      missingColumns: "Faltan columnas: {cols}",
      authRequired: "Inicia sesión como administrador para importar.",
      resultSummary: "Importación: {success} correctas, {failed} fallidas (de {total}).",
      row: "Fila",
      item: "Elemento",
      status: "Estado",
      detail: "Detalle",
      ok: "OK",
      failed: "Error",
      usersTitle: "Importar usuarios (CSV)",
      usersHint:
        "Crea o actualiza cuentas por email. Incluye avatar_url (URL de foto), slug, tags (separados por |). Si el email ya existe, se actualiza el perfil. Acepta columnas alias: foto, photo, nombre, etc.",
      exportUsers: "Exportar usuarios actuales",
      serverConfigError:
        "La importación CSV requiere SUPABASE_SERVICE_ROLE_KEY en Vercel. Ve a Supabase → Project Settings → API → service_role y añádela en Vercel → Environment Variables (Production + Preview). Luego redeploy.",
      listingsTitle: "Importar espacios (CSV)",
      listingsHint:
        "Los emails owner_email y host_email deben existir ya en la plataforma. Si el slug está ocupado, se generará uno alternativo.",
    },
  },
} as const;

export type I18n = typeof es;
